# Generated by Django 5.0.2 on 2024-02-26 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0005_invalidloginlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operationlog',
            name='operation',
            field=models.CharField(choices=[('Create', 'Create'), ('Update', 'Update'), ('Delete', 'Delete')], max_length=20),
        ),
    ]
